version: "3"
networks:
    asylamba:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16

services:
    game:
        container_name: asylamba_game
        build: applications/asylamba-game
        image: asylamba/game
        depends_on:
            - mysql
            - redis
        env_file:
            - asylamba.env
        volumes:
            - "./volumes/apps:/srv/apps"
            - "./volumes/logs/game:/srv/logs"
        ports:
            - "9999:9999"
        networks:
            asylamba:
                ipv4_address: 172.20.0.2

    blackfire:
        container_name: asylamba_blackfire
        image: blackfire/blackfire
        environment:
            # Exposes the host BLACKFIRE_SERVER_ID and TOKEN environment variables.
            - BLACKFIRE_CLIENT_ID
            - BLACKFIRE_CLIENT_TOKEN
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN
        networks:
            asylamba:
                ipv4_address: 172.20.0.3
        ports:
            - "8707:8707"

    phpmyadmin:
        container_name: asylamba_phpmyadmin
        image: nazarpc/phpmyadmin
        environment:
            SESSION_TIMEOUT: 86400
        networks:
            asylamba:
                ipv4_address: 172.20.0.4
        ports:
            - "8082:80"

    # MYSQL Database
    mysql:
        container_name: asylamba_mysql
        build: mysql
        image: asylamba/mysql
        env_file:
            - asylamba.env
        networks:
            asylamba:
                ipv4_address: 172.20.0.5
        ports:
            - "33306:3306"
        volumes:
            # mysql
            - "./volumes/mysql:/var/lib/mysql"

    # Nginx webserver
    nginx:
        container_name: asylamba_nginx
        build: nginx
        image: asylamba/nginx
        depends_on:
            - game
        env_file:
            - asylamba.env
        extra_hosts:
            - "local.asylamba.com:127.0.0.1"
            - "preprod.asylamba.com:127.0.0.1"
            - "s14.asylamba.com:127.0.0.1"
        volumes:
            # applications
            - "./volumes/apps:/srv/apps"
            # nginx
            - "./volumes/ssl:/etc/ssl"
            - "./volumes/html:/usr/share/nginx/html"
            - "./volumes/logs/nginx:/var/log/nginx"
        networks:
            asylamba:
                ipv4_address: 172.20.0.6
        ports:
            - "443:443"
            - "80:80"

    redis:
        container_name: asylamba_redis
        image: redis
        env_file:
            - asylamba.env
        networks:
            asylamba:
                ipv4_address: 172.20.0.7
        ports:
            - "6379:6379"

    redisCommander:
        container_name: asylamba_redis_commander
        image: tenstartups/redis-commander
        command: --redis-host redis
        depends_on:
            - redis
        networks:
            asylamba:
                ipv4_address: 172.20.0.8
        ports:
            - "8081:8081"
