version: "3"
networks:
    asylamba:
        driver: bridge
    chickenbot:
        driver: bridge

services:
    game:
        image: asylamba/game
        container_name: asylamba_game
        restart: always
        depends_on:
            - mysql
        env_file:
            - asylamba.env
        volumes:
            - "./volumes/apps:/srv/apps"
            - "./volumes/logs/game:/srv/logs"
        networks:
            - asylamba

    phpmyadmin:
        image: nazarpc/phpmyadmin
        container_name: asylamba_phpmyadmin
        networks:
            - asylamba
        ports:
            - "8082:80"

    # MYSQL Database
    mysql:
        container_name: asylamba_mysql
        image: asylamba/mysql
        env_file:
            - asylamba.env
        networks:
            - asylamba
        ports:
            - "33306:3306"
        volumes:
            # mysql
            - "./volumes/mysql:/var/lib/mysql"

    # Nginx webserver
    nginx:
        container_name: asylamba_nginx
        image: asylamba/nginx
        depends_on:
            - bot
            - game
        env_file:
            - asylamba.env
        extra_hosts:
            - "chickenbot.asylamba.com:127.0.0.1"
            - "preprod.asylamba.com:127.0.0.1"
            - "s14.asylamba.com:127.0.0.1"
        volumes:
            - "./volumes/ssl:/etc/letsencrypt"
            - "./volumes/apps:/srv/apps"
            - "./volumes/html:/usr/share/nginx/html"
            - "./volumes/logs/nginx:/var/log/nginx"
        networks:
            - asylamba
            - chickenbot
        ports:
            - "443:443"
            - "80:80"

    redis:
        container_name: asylamba_redis
        image: redis
        command: redis-server --requirepass $REDIS_PASSWORD
        env_file:
            - asylamba.env
        networks:
            - asylamba
        ports:
            - "6379:6379"

    bot:
        container_name: chicken_bot
        image: asylamba/chickenbot
        working_dir: /srv/app
        env_file:
          - asylamba.env
        networks:
          - chickenbot
